language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

before_install:
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
  - unzip protoc-3.1.0-linux-x86_64.zip
  - nvm install 6.9.4
  - npm install npm@latest -g
  - npm install -g protobufjs
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - export GOPATH=$(pwd)/web:$GOPATH
  - export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH
  - export PATH=$(pwd)/bin:$PATH
  - ./pbuf.sh

install:
  - go get -d ./web/...
  - cd ./client-side && npm install && cd ..

script:
  - go test -v ./web/src/memmi/card/...
  - go test -v ./web/src/memmi/user/...
  - go test -v ./web/src/memmi/request/...
  - go test -v ./web/src/memmi/factory/...
  - cd ./client-side && npm test && cd ..
