language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

before_install:
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
  - unzip protoc-3.1.0-linux-x86_64.zip
  - nvm install 6.9.4
  - npm install npm@latest -g
  - npm install -g protobufjs
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - export GOPATH=$(pwd)/web
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib
  - export PATH=$PATH:$(pwd)/bin
  - ./pbuf.sh

install:
  - go get -d ./web/...

script:
  - go test -v ./web/...
