language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

cache:
  directories:
    - $HOME/protobuf

before_install:
  - nvm install 6.9.4
  - npm install npm@latest -g
  - npm install -g protobufjs
  - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
  - export GOPATH=$(pwd)/web
  - ./install_pbuf.sh
  - ./pbuf.sh

install:
  - go get -d ./web/...

script:
  - go test -v ./web/...
