language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install latest
  - npm install -g protobufjs
  - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
  - export GOPATH=$(pwd)/web
  - ./pbuf.sh

install:
  - go get -d ./web/...

script:
  - go test -v ./web/...
