[app]
server = ":8081"

[router]
logType = "console"
handlers = ["cardSet", "card"]

[cardManagement]
type = "inmemory"
seed = true

[userManagement]
type = "inmemory"
seed = true

[factory]
useSingletons = true

[logging]
logType = "console"
logEndPoint = ""
logSampling = 1.0
