[app]
server = ":8081"

[router]
logType = "console"
handlers = ["cardSet", "card"]

[cardManagement]
type = "inmemory"
seed = true

[userManagement]
type = "inmemory"
seed = true

[factory]
useSingletons = true

[logging]
type = "console"
endpoint = ""
samplingRate = 1.0
level = "info"
