[app]
server = ":80"

[router]
logType = "console"
handlers = ["cardSet", "card"]

[cardManagement]
type = "inmemory"
seed = false

[userManagement]
type = "inmemory"
seed = false

[factory]
useSingletons = true
