[app]
server = ":80"

[router]
handlers = ["cardSet", "card"]

[cardManagement]
type = "inmemory"
seed = false

[userManagement]
type = "inmemory"
seed = false

[factory]
useSingletons = true

[logging]
logType = "console"
logEndPoint = ""
logSampling = 1.0
