[app]
server = ":80"

[router]
handlers = ["cardSet", "card"]

[cardManagement]
type = "inmemory"
seed = false

[userManagement]
type = "inmemory"
seed = false

[factory]
useSingletons = true

[logging]
type = "console"
endpoint = ""
samplingRate = 1.0
